# hostname (and path) to the root eg. http://spf13.com/
baseurl = "http://www.tutysara.net/"

# Site title
title = "TUTYSARA'S SPACE"

# Copyright
copyright = "(c) 2018 tutysara"

# Language
languageCode = "en-EN"

# Metadata format
# "yaml", "toml", "json"
metaDataFormat = "yaml"

# Theme to use (located in /themes/THEMENAME/)
#theme = "hugo-bootstrap"
theme = "theme-beautifulhugo"

googleAnalytics = "UA-34510369-1"

# Pagination
pagination.pagerSize = 3
pagination.path = "page"

# Enable Disqus integration
#disqusShortname = "tutysarablog"

#chroma
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsStyle = "trac"

# pygments
#pygmentsUseClassic = true

# hugo gen chromastyles --style=manni > syntax.css
[permalinks]
    post = "posts/:year/:month/:day/:slug/"
    code = "/:slug/"

[Params]
    subtitle = "what I learned that is worth sharing and useful for me/world or both"
    logo = "/img/avatar-favicon.png"
    favicon = "img/favicon.ico"
    dateFormat = "January 2, 2006"
    commit = true
    rss = true
    comments = true
    readingTime = true
    gcse = true

[Author]
    name = "tutysara"
    website = "tutysara.net"
    email = "tutysara at google mail.com"
    googleplus = "+tutysara"
    github = "tutysara"
    twitter = "tutysara"
  

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3

#https://api.staticman.net/v2/connect/tutysara/tutysara.net.comments
[Params.staticman]
    api = "https://api.staticman.net/v2/entry/tutysara/tutysara.net.comments/master/comments"
    pulls =  "https://github.com/tutysara/tutysara.net.comments/pulls"
